notifications: never

language: python
python:
    - "2.7"
before_install:
    - pip install pytest pytest-travis-fold responses freezegun vcrpy jsonpickle requests-mock urltools
    
#install: pip install -r requirements.txt
before_script: cd ./nzbhydra/tests
script:
    - python startTests.py