language: python
python:
    - "2.7"
branches:
  only:
    - develop
before_install:
    - pip install pytest pytest-cov pytest-travis-fold
#install: pip install -r requirements.txt
before_script: cd ./nzbhydra/tests
script:
    - python startTests.py